version: '1'
services:
  adminer:
    image: adminer
    container_name: csv_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - csv_network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: csv_sql_server
    environment:
      SA_PASSWORD: MyP@ssw0rd123
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - csv_network

# DADOS DO SQL SERVER
# Server: localhost
# Server2: csv_sql_server
# Port: 1433
# Usuário: sa
# Senha: MyP@ssw0rd123

networks:
  csv_network:
    driver: bridge